//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikBlazorDemos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TelerikDemoMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelerikDemoMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelerikBlazorDemos.Resources.TelerikDemoMessages", typeof(TelerikDemoMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree to Terms*:.
        /// </summary>
        public static string Form_AcceptTerms {
            get {
                return ResourceManager.GetString("Form_AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree with the terms..
        /// </summary>
        public static string Form_AcceptTerms_Error {
            get {
                return ResourceManager.GetString("Form_AcceptTerms_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date*:.
        /// </summary>
        public static string Form_BirthDate {
            get {
                return ResourceManager.GetString("Form_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify birth date..
        /// </summary>
        public static string Form_BirthDate_Error {
            get {
                return ResourceManager.GetString("Form_BirthDate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Form_Clear {
            get {
                return ResourceManager.GetString("Form_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email*:.
        /// </summary>
        public static string Form_Email {
            get {
                return ResourceManager.GetString("Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify email..
        /// </summary>
        public static string Form_Email_Error {
            get {
                return ResourceManager.GetString("Form_Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name*:.
        /// </summary>
        public static string Form_FirstName {
            get {
                return ResourceManager.GetString("Form_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify your first name..
        /// </summary>
        public static string Form_FirstName_Error {
            get {
                return ResourceManager.GetString("Form_FirstName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name*:.
        /// </summary>
        public static string Form_LastName {
            get {
                return ResourceManager.GetString("Form_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify your last name..
        /// </summary>
        public static string Form_LastName_Error {
            get {
                return ResourceManager.GetString("Form_LastName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name:.
        /// </summary>
        public static string Form_MiddleName {
            get {
                return ResourceManager.GetString("Form_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password*:.
        /// </summary>
        public static string Form_Password {
            get {
                return ResourceManager.GetString("Form_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should be at least 8 characters..
        /// </summary>
        public static string Form_Password_Error {
            get {
                return ResourceManager.GetString("Form_Password_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a product name.
        /// </summary>
        public static string ProductBindingModel_Name_RequiredError {
            get {
                return ResourceManager.GetString("ProductBindingModel_Name_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cost should be in range {1} - {2}.
        /// </summary>
        public static string ProductBindingModel_StandardCost_RangeError {
            get {
                return ResourceManager.GetString("ProductBindingModel_StandardCost_RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is too long.
        /// </summary>
        public static string ProductCategory_Name_LengthError {
            get {
                return ResourceManager.GetString("ProductCategory_Name_LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        public static string ProductCategory_Name_RequiredError {
            get {
                return ResourceManager.GetString("ProductCategory_Name_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Step.
        /// </summary>
        public static string Stepper_Label1 {
            get {
                return ResourceManager.GetString("Stepper_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Step.
        /// </summary>
        public static string Stepper_Label2 {
            get {
                return ResourceManager.GetString("Stepper_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Step.
        /// </summary>
        public static string Stepper_Label3 {
            get {
                return ResourceManager.GetString("Stepper_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} does not match..
        /// </summary>
        public static string Validation_CompareError {
            get {
                return ResourceManager.GetString("Validation_CompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not valid..
        /// </summary>
        public static string Validation_EmailError {
            get {
                return ResourceManager.GetString("Validation_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is too short..
        /// </summary>
        public static string Validation_MinLengthError {
            get {
                return ResourceManager.GetString("Validation_MinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        public static string Validation_RequiredError {
            get {
                return ResourceManager.GetString("Validation_RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Step Content.
        /// </summary>
        public static string Wizard_StepContent1 {
            get {
                return ResourceManager.GetString("Wizard_StepContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Step Content.
        /// </summary>
        public static string Wizard_StepContent2 {
            get {
                return ResourceManager.GetString("Wizard_StepContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Step Content.
        /// </summary>
        public static string Wizard_StepContent3 {
            get {
                return ResourceManager.GetString("Wizard_StepContent3", resourceCulture);
            }
        }
    }
}
